"""Add league, club, player image_url fields to respective models

Revision ID: a8603aea617e
Revises: 150e4b970716
Create Date: 2022-05-30 14:00:30.847911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8603aea617e'
down_revision = '150e4b970716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('club_image_url', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'club', ['club_image_url'])
    op.add_column('league', sa.Column('league_image_url', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'league', ['league_image_url'])
    op.add_column('player', sa.Column('player_image_url', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'player', ['player_image_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'player_image_url')
    op.drop_constraint(None, 'league', type_='unique')
    op.drop_column('league', 'league_image_url')
    op.drop_constraint(None, 'club', type_='unique')
    op.drop_column('club', 'club_image_url')
    # ### end Alembic commands ###
