"""Remove Player model from models.py

Revision ID: eb8c7c481eb8
Revises: bcb53d73eb01
Create Date: 2022-06-30 11:33:41.448452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8c7c481eb8'
down_revision = 'bcb53d73eb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name='player_club_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='player_pkey')
    )
    # ### end Alembic commands ###
